name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: git config --global user.email "suggesttosnazzy@gmail.com"
      - run: git config --global user.name "Snazzah"
      - run: git remote set-url origin https://Snazzah:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git

      - run: npm i
      - run: npm run deploy

  lint:
    name: Lint stable branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: npm i
      - run: npm run lint

      - uses: EndBug/add-and-commit@v4
        with:
          add: src
          message: '[auto] Lint source code'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
